"""AI reasoning layer for the adaptive coach (Lot D2) — non-destructive.

Wraps the rule-based D1 verdict (``readiness.daily_verdict``) with a short,
athlete-facing explanation generated by the Claude API. The rule verdict is the
**anchor**: the agent may refine the tone, escalate caution (e.g. GREEN -> AMBER
when the context warrants it), or explain the call, but it can NEVER make the
verdict *less* cautious than the rule decided. In particular a RED can never be
downgraded to AMBER or GREEN — that invariant is enforced in code
(``_reconcile_verdict``), independently of whatever the model returns.

Nothing here mutates a training plan. The LLM call is isolated in ``_call_llm``
so tests can mock it without any network access. The default model is
Haiku 4.5 (cheapest tier; spec 03 §3 Lot D2); pass ``model=`` to override.
"""

import json
import logging
import os
from typing import Any, Optional

from pydantic import BaseModel

from .readiness import DailyVerdict, Verdict, _modification

logger = logging.getLogger(__name__)

# Default model: Haiku 4.5 for cost (spec 03 §3 Lot D2 — Sonnet only if needed).
DEFAULT_MODEL = "claude-haiku-4-5"

# Severity ordering used to clamp the agent so it never relaxes the rule verdict.
_SEVERITY = {Verdict.GREEN: 0, Verdict.AMBER: 1, Verdict.RED: 2}

# JSON schema the model must fill. ``insufficient_baseline`` is deliberately not
# an option — the agent only runs when a real baseline exists.
_OUTPUT_SCHEMA = {
    "type": "object",
    "properties": {
        "verdict": {"type": "string", "enum": ["green", "amber", "red"]},
        "headline": {"type": "string", "description": "Three to six word summary"},
        "rationale": {
            "type": "string",
            "description": "One or two short sentences explaining the call",
        },
        "adjustment": {
            "type": "string",
            "description": "Concrete, non-applied tweak to today's session",
        },
    },
    "required": ["verdict", "headline", "rationale", "adjustment"],
    "additionalProperties": False,
}

_SYSTEM_PROMPT = (
    "On est l'assistant d'entraînement de HillsRun. À partir d'un verdict de "
    "disponibilité déjà calculé par une règle physiologique (VFC du matin vs "
    "ligne de base individuelle), on rédige une explication courte et concrète "
    "pour l'athlète. Le verdict de la règle fait autorité : on peut renforcer "
    "la prudence mais jamais l'assouplir, et on ne transforme JAMAIS un RED en "
    "vert ou orange. Ton neutre et précis, pas d'emojis, pas de tutoiement ni "
    "de vouvoiement, deux phrases maximum pour la justification."
)


class AgentRecommendation(BaseModel):
    """Structured, non-applied recommendation returned by the agent."""

    verdict: Verdict  # reconciled — never less cautious than the rule anchor
    headline: str
    rationale: str
    adjustment: str
    suggested_modification: dict  # mirrors the reconciled verdict (advisory)
    model: str  # Claude model id used (or "" when no LLM call was made)
    anchored: bool  # True when the rule verdict overrode a softer agent proposal


def _reconcile_verdict(anchor: Verdict, proposed: Verdict) -> tuple[Verdict, bool]:
    """Clamp the agent's proposal so it never relaxes the rule verdict.

    Args:
        anchor: The authoritative rule-based verdict from D1.
        proposed: The verdict the model returned.

    Returns:
        ``(final_verdict, anchored)`` — ``anchored`` is True when the agent
        tried to soften the call and was overridden (notably a RED downgrade).
    """
    # insufficient_baseline is authoritative both ways — the agent has no
    # baseline to reason about, so its verdict (if any) is discarded.
    if anchor is Verdict.INSUFFICIENT_BASELINE:
        return (
            Verdict.INSUFFICIENT_BASELINE,
            proposed is not Verdict.INSUFFICIENT_BASELINE,
        )
    if proposed is Verdict.INSUFFICIENT_BASELINE:
        return anchor, True
    # The agent may match or escalate caution, never reduce it.
    if _SEVERITY[proposed] < _SEVERITY[anchor]:
        return anchor, True
    return proposed, False


def _call_llm(
    client: Any,
    *,
    system: str,
    user: str,
    model: str,
    max_tokens: int = 400,
) -> dict:
    """Run one structured Claude call and return the parsed JSON object.

    Isolated so tests can patch it (no network). Uses ``output_config.format``
    with a JSON schema, then parses the single text block. Haiku does not take
    the ``effort``/``thinking`` knobs, so none are sent.

    Args:
        client: An ``anthropic.Anthropic`` client (or a stand-in for tests).
        system: System prompt.
        user: User message content.
        model: Claude model id.
        max_tokens: Output cap (short — the response is a few sentences).

    Returns:
        The decoded JSON object matching ``_OUTPUT_SCHEMA``.
    """
    response = client.messages.create(
        model=model,
        max_tokens=max_tokens,
        system=system,
        messages=[{"role": "user", "content": user}],
        output_config={"format": {"type": "json_schema", "schema": _OUTPUT_SCHEMA}},
    )
    text = next((b.text for b in response.content if b.type == "text"), "")
    return json.loads(text)


def _build_user_prompt(
    base_verdict: DailyVerdict,
    planned_session: Optional[dict],
    recent_context: Optional[list[dict]],
) -> str:
    """Render the signals, planned session, and 3-day context as a prompt."""
    lines = [
        f"Verdict de la règle : {base_verdict.verdict.value.upper()}.",
        f"Motif de la règle : {base_verdict.reason}",
    ]
    if base_verdict.hrv_value is not None:
        band = ""
        if (
            base_verdict.baseline_low is not None
            and base_verdict.baseline_high is not None
        ):
            band = (
                f" (ligne de base {base_verdict.baseline_low:.0f}-"
                f"{base_verdict.baseline_high:.0f} ms)"
            )
        lines.append(f"VFC du matin : {base_verdict.hrv_value:.0f} ms{band}.")

    if planned_session:
        title = planned_session.get("title") or "séance"
        sport = planned_session.get("sport_type") or ""
        duration = planned_session.get("planned_duration_seconds")
        dur_txt = f", {duration // 60} min" if duration else ""
        lines.append(f"Séance prévue aujourd'hui : {title} ({sport}{dur_txt}).")
    else:
        lines.append("Aucune séance prévue aujourd'hui.")

    if recent_context:
        parts = []
        for c in recent_context:
            label = f"{c.get('date')}: {str(c.get('verdict', '?')).upper()}"
            hrv = c.get("hrv_value")
            if hrv is not None:
                label += f" VFC {hrv:.0f}"
            parts.append(label)
        lines.append(f"Trois derniers jours : {'; '.join(parts)}.")

    lines.append(
        "Rédiger headline, rationale et adjustment. Le verdict renvoyé doit "
        "rester au moins aussi prudent que celui de la règle."
    )
    return "\n".join(lines)


def build_agent_recommendation(
    base_verdict: DailyVerdict,
    *,
    planned_session: Optional[dict] = None,
    recent_context: Optional[list[dict]] = None,
    client: Any = None,
    model: str = DEFAULT_MODEL,
) -> AgentRecommendation:
    """Produce a structured, anchored recommendation for ``base_verdict``.

    The rule verdict anchors the result; the agent only explains and may
    escalate caution. When the baseline is insufficient, no LLM call is made.

    Args:
        base_verdict: The authoritative D1 verdict.
        planned_session: Today's planned workout row (optional).
        recent_context: Prior days' verdicts/HRV, oldest first (optional).
        client: Anthropic client; created from the env if omitted.
        model: Claude model id (defaults to Haiku 4.5).

    Returns:
        An ``AgentRecommendation`` whose ``verdict`` is never less cautious than
        ``base_verdict`` (a RED can never be relaxed).
    """
    # No baseline -> nothing to reason about; echo the rule, skip the LLM cost.
    if base_verdict.verdict is Verdict.INSUFFICIENT_BASELINE:
        return AgentRecommendation(
            verdict=Verdict.INSUFFICIENT_BASELINE,
            headline="Historique VFC insuffisant",
            rationale=base_verdict.reason,
            adjustment="On conserve la séance prévue.",
            suggested_modification=base_verdict.suggested_modification,
            model="",
            anchored=False,
        )

    if client is None:
        import anthropic  # lazy import: only needed when actually calling the API

        client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

    user_prompt = _build_user_prompt(base_verdict, planned_session, recent_context)
    raw = _call_llm(client, system=_SYSTEM_PROMPT, user=user_prompt, model=model)

    proposed = Verdict(raw["verdict"])
    final, anchored = _reconcile_verdict(base_verdict.verdict, proposed)

    return AgentRecommendation(
        verdict=final,
        headline=str(raw.get("headline", "")).strip(),
        rationale=str(raw.get("rationale", "")).strip(),
        adjustment=str(raw.get("adjustment", "")).strip(),
        suggested_modification=_modification(final),
        model=model,
        anchored=anchored,
    )
